const state={platform:'all',category:'all',search:'',pending:false,page:1,pageSize:25,items:[],filteredTotal:0,currentId:null,progress:null};
const $=s=>document.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
const pretty=value=>Array.isArray(value)?value.join(', '):(typeof value==='object'?JSON.stringify(value,null,2):String(value));
let searchTimer,toastTimer;

async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
function setSave(text,kind=''){const node=$('#save-state');node.textContent=text;node.className=`save-state ${kind}`}
function toast(text){const node=$('#toast');node.textContent=text;node.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('show'),2600)}
function query(){const p=new URLSearchParams({platform:state.platform,category:state.category,search:state.search,pending:String(state.pending),page:String(state.page),page_size:String(state.pageSize)});return p.toString()}

async function loadResources(preferredId=null){setSave('Loading index…','saving');try{const data=await api(`/api/resources?${query()}`);Object.assign(state,{items:data.items,filteredTotal:data.filtered_total,progress:data.progress});renderPlatforms(data.platform_counts);renderProgress();renderList();renderPager();const target=preferredId&&state.items.some(x=>x.id===preferredId)?preferredId:(state.items.some(x=>x.id===state.currentId)?state.currentId:state.items[0]?.id);if(target)await selectResource(target);else renderEmpty('No resources match these filters.');setSave('Server overlay ready','')}catch(error){setSave(error.message,'error');renderEmpty(error.message)}}
function renderProgress(){const p=state.progress||{total:0,decided:0,pending:0,accept:0,maybe:0,reject:0};const pct=p.total?Math.round(p.decided/p.total*100):0;$('#progress-label').textContent=`${p.decided.toLocaleString()} / ${p.total.toLocaleString()} reviewed`;$('#progress-percent').textContent=`${pct}%`;$('#progress-bar').style.width=`${pct}%`;$('#count-accept').textContent=p.accept;$('#count-maybe').textContent=p.maybe;$('#count-reject').textContent=p.reject;$('#count-pending').textContent=p.pending}
function renderPlatforms(counts){const tabs=$('#platform-tabs');const entries=[['all',Object.values(counts).reduce((a,b)=>a+b,0)],...Object.entries(counts)];tabs.innerHTML=entries.map(([name,count])=>`<button class="platform-tab ${state.platform===name?'active':''}" data-platform="${esc(name)}">${name==='all'?'All platforms':esc(name)} <b>${count}</b></button>`).join('');tabs.querySelectorAll('button').forEach(button=>button.onclick=()=>{state.platform=button.dataset.platform;state.page=1;loadResources()})}
function renderList(){const list=$('#resource-list');list.innerHTML=state.items.map(item=>{const decision=item.decision?.decision||'';const symbol=decision==='accept'?'✓':decision==='reject'?'×':decision==='maybe'?'~':'';return `<button class="resource-item ${item.id===state.currentId?'active':''}" data-id="${item.id}" data-cat="${item.ada_category}" role="option"><span class="dot"></span><span><span class="item-title">${esc(item.title)}</span><span class="item-meta">${esc(item.platform)} · ${esc(item.artifact_level)}</span></span><span class="decision-mark ${decision}">${symbol}</span></button>`}).join('');list.querySelectorAll('button').forEach(button=>button.onclick=()=>{selectResource(button.dataset.id);if(window.matchMedia('(max-width:680px)').matches)setTimeout(()=>document.querySelector('.review-main').scrollIntoView({behavior:'smooth'}),0)})}
function renderPager(){const pages=Math.max(1,Math.ceil(state.filteredTotal/state.pageSize));$('#page-label').textContent=`Page ${state.page} / ${pages} · ${state.filteredTotal.toLocaleString()}`;$('#page-prev').disabled=state.page<=1;$('#page-next').disabled=state.page>=pages}
function renderEmpty(message){state.currentId=null;$('#review-card').className='review-card empty';$('#review-card').innerHTML=`<div class="empty-state"><p>${esc(message)}</p></div>`}

async function selectResource(id){state.currentId=id;renderList();setSave('Loading evidence…','saving');try{const item=await api(`/api/resources/${encodeURIComponent(id)}`);renderDetail(item);setSave('Server overlay ready','')}catch(error){setSave(error.message,'error')}}
function renderDetail(item){const card=$('#review-card');card.className='review-card';const metadata={stable_id:item.stable_id,lifecycle:item.lifecycle,relevance_status:item.relevance_status,artifact_level:item.artifact_level,...item.metadata};const decision=item.decision||{};card.innerHTML=`
<header class="resource-head"><div><div class="resource-kicker"><span>${esc(item.platform)}</span><span>·</span><span>${esc(item.artifact_level)}</span><span class="badge ${item.ada_category}">${esc(item.ada_label)}</span></div><h2>${esc(item.title)}</h2><a class="source-link" href="${esc(item.source_url)}" target="_blank" rel="noopener noreferrer">Open canonical source ↗</a><div class="path-line">${esc(item.path)}</div></div><div class="nav-arrows"><button id="previous-resource" title="Previous resource">←</button><button id="next-resource" title="Next resource">→</button></div></header>
<section class="ada-audit"><strong>Ada categorization · ${esc(item.ada_label)}</strong>${esc(item.ada_reason)}</section>
<div class="meta-strip"><span class="meta-pill">${esc(item.lifecycle)}</span><span class="meta-pill">${esc(item.relevance_status)}</span><span class="meta-pill">${esc(item.artifact_level)}</span><span class="meta-pill">${esc(item.platform)}</span></div>
<section class="evidence-grid"><div class="pane"><div class="pane-head"><span>Retained evidence / summary</span><span>${item.evidence.length.toLocaleString()} chars</span></div><div class="evidence-body">${esc(item.evidence)}</div></div><div class="pane"><div class="pane-head"><span>Canonical metadata</span><span>read only</span></div><div class="metadata-body">${Object.entries(metadata).map(([key,value])=>`<div class="metadata-row"><span class="metadata-key">${esc(key)}</span><div class="metadata-value">${esc(pretty(value))}</div></div>`).join('')}</div></div></section>
<section class="decision-panel"><div class="decision-top"><h3>Human decision</h3><span class="shortcut-note">A accept · M maybe · R reject</span></div><div class="decision-buttons"><button class="decision-button accept ${decision.decision==='accept'?'active':''}" data-decision="accept">Accept <small>find more like this</small></button><button class="decision-button maybe ${decision.decision==='maybe'?'active':''}" data-decision="maybe">Maybe <small>hold for later</small></button><button class="decision-button reject ${decision.decision==='reject'?'active':''}" data-decision="reject">Reject <small>avoid similar</small></button></div><label class="comment-label">Reviewer comment<textarea id="review-comment" placeholder="Why does this work—or not—for the corpus?">${esc(decision.comment||'')}</textarea></label><div class="saved-at">${decision.updated_at?`Saved server-side ${esc(decision.updated_at)}`:'Pending · no overlay decision saved'}</div></section>`;
card.querySelectorAll('[data-decision]').forEach(button=>button.onclick=()=>saveDecision(item,button.dataset.decision));$('#previous-resource').onclick=()=>move(-1);$('#next-resource').onclick=()=>move(1)}
async function saveDecision(item,decision){const comment=$('#review-comment').value;setSave('Saving overlay…','saving');try{const result=await api('/api/decisions',{method:'POST',body:JSON.stringify({resource_id:item.id,decision,comment})});item.decision=result.saved;setSave('Saved server-side','saved');toast(`${decision[0].toUpperCase()+decision.slice(1)} saved`);await loadResources(item.id)}catch(error){setSave(error.message,'error');toast(`Save failed: ${error.message}`)}}
function move(delta){const index=state.items.findIndex(item=>item.id===state.currentId);const target=state.items[index+delta];if(target)selectResource(target.id);else if(delta>0&&!$('#page-next').disabled){state.page++;loadResources()}else if(delta<0&&!$('#page-prev').disabled){state.page--;loadResources()}}
async function bulk(decision){const label=decision==='accept'?'Works':'Doesn\'t fit';const ids=state.items.map(item=>item.id);if(!ids.length)return;setSave('Saving safe bulk decisions…','saving');try{const result=await api('/api/bulk',{method:'POST',body:JSON.stringify({resource_ids:ids,decision,comment:`Safe bulk ${decision}: matched Ada category ${label}.`})});toast(`${result.saved.length} saved · ${result.skipped.length} skipped as unsafe`);await loadResources()}catch(error){setSave(error.message,'error');toast(error.message)}}

$('#category-tabs').querySelectorAll('button').forEach(button=>button.onclick=()=>{$('#category-tabs').querySelectorAll('button').forEach(x=>x.classList.remove('active'));button.classList.add('active');state.category=button.dataset.category;state.page=1;loadResources()});
$('#pending-only').onchange=event=>{state.pending=event.target.checked;state.page=1;loadResources()};
$('#search').oninput=event=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.search=event.target.value.trim();state.page=1;loadResources()},220)};
$('#page-prev').onclick=()=>{if(state.page>1){state.page--;loadResources()}};$('#page-next').onclick=()=>{state.page++;loadResources()};
$('#bulk-accept').onclick=()=>bulk('accept');$('#bulk-reject').onclick=()=>bulk('reject');
document.addEventListener('keydown',event=>{if(event.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){event.preventDefault();$('#search').focus();return}if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(event.key.toLowerCase()==='a')document.querySelector('[data-decision="accept"]')?.click();if(event.key.toLowerCase()==='m')document.querySelector('[data-decision="maybe"]')?.click();if(event.key.toLowerCase()==='r')document.querySelector('[data-decision="reject"]')?.click();if(event.key==='ArrowLeft')move(-1);if(event.key==='ArrowRight')move(1)});
loadResources();
